os:
  - linux
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script:
- npm test
after_script:
- npm i bower && bower install --silent
- polymer test --plugin sauce --job-name \"variables-manager:local-test\"
